export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const GET_USER_RPOFILE_REQUEST = "GET_USER_RPOFILE_REQUEST"
export const GET_USER_RPOFILE_SUCCESS = "GET_USER_RPOFILE_SUCCESS"
export const GET_USER_RPOFILE_FAILURE = "GET_USER_RPOFILE_FAILURE"